spring:
  datasource:
    platform: PostgreSQL
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library-prod
    username: mvargas
    password:
  jpa:
    database: PostgreSQL
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
